kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: fajar4561/saciku:latest
   environment:
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     TG_TOKEN:
       from_secret: TG_TOKEN
     AWAL:
       from_secret: AWAL
     AKHIR:
       from_secret: AKHIR
   commands:
      - git config --global user.name "$AWAL"
      - git config --global user.email "kuplemarkeple@gmail.com"
      - git clone --depth=1 https://$AWAL:$AKHIR@github.com/xootkama/android_kernel_realme_sdm710-1 new
      - curl https://raw.githubusercontent.com/xootkama/script_clang_kernel_compile/main/script_build.sh --output a.sh
      - mkdir gcc
      - cd gcc
      - curl https://xootkama.xootkama.workers.dev/0:/11.2.0.zip --output gcc.zip
      - unzip gcc.zip
      - cd ..
      - cd new 
      - curl https://raw.githubusercontent.com/xootkama/script_clang_kernel_compile/main/script_build.sh --output a.sh
      - curl https://raw.githubusercontent.com/xootkama/My-kernel-builder/ts/build.sh > run.sh
      - bash run.sh
